PROMPTS = [
    {
        "id": "exercise",
        "topic": "the benefits of exercise",
        "base_instruction": "Write a short response about the benefits of exercise.",
        "ordered_checks": [
            (("long_word_per_sentence", "sentences_contain_long_word", {"min_length": 5}), "Each sentence must contain at least one word with 5 or more letters."),
            (("min_20_unique", "min_unique_words", {"min_unique": 20}), "You must use at least 20 unique words."),
            (("max_word_freq_3", "max_word_frequency", {"max_count": 3}), "No word may appear more than 3 times in your entire response."),
            (("no_commas", "forbidden_char", {"char": ","}), "Do not use any commas."),
            (("all_lowercase", "all_lowercase", {}), "Your entire response must be in all lowercase."),
            (("keyword_energy_2x", "keyword_min_count", {"word": "energy", "min_count": 2}), "Include the word 'energy' at least twice."),
            (("exactly_5_sentences", "count_sentences", {"target": 5}), "Your response must be exactly 5 sentences long."),
            (("words_per_sentence_8_15", "words_per_sentence_range", {"min_w": 8, "max_w": 15}), "Each sentence must be between 8 and 15 words long."),
            (("different_start_letters", "sentences_start_different_letter", {}), "Each sentence must start with a different letter."),
        ],
    },
    {
        "id": "book_review",
        "topic": "a book review",
        "base_instruction": "Write a short review of a book you have read.",
        "ordered_checks": [
            (("long_word_per_sentence", "sentences_contain_long_word", {"min_length": 5}), "Each sentence must contain at least one word with 5 or more letters."),
            (("min_25_unique", "min_unique_words", {"min_unique": 25}), "You must use at least 25 unique words."),
            (("max_word_freq_3", "max_word_frequency", {"max_count": 3}), "No word may appear more than 3 times in your entire response."),
            (("no_commas", "forbidden_char", {"char": ","}), "Do not use any commas."),
            (("all_uppercase", "all_uppercase", {}), "Your entire response must be in all uppercase letters."),
            (("keyword_RECOMMEND", "keyword_min_count_case_sensitive", {"word": "RECOMMEND", "min_count": 1}), "Include the word 'RECOMMEND' at least once."),
            (("exactly_4_sentences", "count_sentences", {"target": 4}), "Your response must be exactly 4 sentences long."),
            (("words_per_sentence_10_20", "words_per_sentence_range", {"min_w": 10, "max_w": 20}), "Each sentence must be between 10 and 20 words long."),
            (("different_start_letters", "sentences_start_different_letter", {}), "Each sentence must start with a different letter."),
        ],
    },
    {
        "id": "language_tips",
        "topic": "tips for learning a new language",
        "base_instruction": "Give tips for learning a new language.",
        "ordered_checks": [
            (("long_word_per_tip", "numbered_items_contain_long_word", {"min_length": 5}), "Each tip must contain at least one word with 5 or more letters."),
            (("min_15_unique", "min_unique_words", {"min_unique": 15}), "You must use at least 15 unique words."),
            (("max_word_freq_3", "max_word_frequency", {"max_count": 3}), "No word may appear more than 3 times in your entire response."),
            (("no_letter_z", "forbidden_char_insensitive", {"char": "z"}), "Do not use the letter 'z' anywhere in your response."),
            (("exactly_3_numbered", "count_numbered_items", {"target": 3}), "Give exactly 3 tips. Number each tip starting from 1."),
            (("tip_words_10_20", "numbered_items_word_range", {"min_w": 10, "max_w": 20}), "Each tip must be between 10 and 20 words long."),
            (("each_tip_one_sentence", "numbered_items_one_sentence", {}), "Each tip must be exactly one sentence."),
        ],
    },
    {
        "id": "season",
        "topic": "describing a favorite season",
        "base_instruction": "Describe your favorite season.",
        "ordered_checks": [
            (("long_word_per_sentence", "sentences_contain_long_word", {"min_length": 5}), "Each sentence must contain at least one word with 5 or more letters."),
            (("min_25_unique", "min_unique_words", {"min_unique": 25}), "You must use at least 25 unique words."),
            (("max_word_freq_3", "max_word_frequency", {"max_count": 3}), "No word may appear more than 3 times in your entire response."),
            (("no_exclamation", "forbidden_char", {"char": "!"}), "Do not use any exclamation marks."),
            (("keyword_weather", "keyword_min_count", {"word": "weather", "min_count": 1}), "Include the word 'weather' at least once."),
            (("exactly_4_sentences", "count_sentences", {"target": 4}), "Your response must be exactly 4 sentences long."),
            (("words_per_sentence_10_20", "words_per_sentence_range", {"min_w": 10, "max_w": 20}), "Each sentence must be between 10 and 20 words long."),
            (("different_start_letters", "sentences_start_different_letter", {}), "Each sentence must start with a different letter."),
            (("ends_with_phrase", "ends_with_phrase", {"phrase": "That is why I love this season more than any other."}), "Finish your response with the exact phrase 'That is why I love this season more than any other.'"),
        ],
    },
    {
        "id": "recycling",
        "topic": "why recycling is important",
        "base_instruction": "Write a short response about why recycling is important.",
        "ordered_checks": [
            (("long_word_per_sentence", "sentences_contain_long_word", {"min_length": 5}), "Each sentence must contain at least one word with 5 or more letters."),
            (("min_25_unique", "min_unique_words", {"min_unique": 25}), "You must use at least 25 unique words."),
            (("max_word_freq_3", "max_word_frequency", {"max_count": 3}), "No word may appear more than 3 times in your entire response."),
            (("no_exclamation", "forbidden_char", {"char": "!"}), "Do not use any exclamation marks."),
            (("all_lowercase", "all_lowercase", {}), "Your entire response must be in all lowercase."),
            (("keyword_environment_3x", "keyword_min_count", {"word": "environment", "min_count": 3}), "Include the word 'environment' at least 3 times."),
            (("exactly_5_sentences", "count_sentences", {"target": 5}), "Your response must be exactly 5 sentences long."),
            (("words_per_sentence_8_15", "words_per_sentence_range", {"min_w": 8, "max_w": 15}), "Each sentence must be between 8 and 15 words long."),
            (("different_start_letters", "sentences_start_different_letter", {}), "Each sentence must start with a different letter."),
        ],
    },
    {
        "id": "horned_dairy_animal",
        "topic": "a small horned dairy animal",
        "base_instruction": "Write a field guide entry about a small horned dairy animal.",
        "ordered_checks": [
            (("long_word_per_sentence", "sentences_contain_long_word", {"min_length": 5}), "Each sentence must contain at least one word with 5 or more letters."),
            (("min_25_unique", "min_unique_words", {"min_unique": 25}), "You must use at least 25 unique words."),
            (("max_word_freq_3", "max_word_frequency", {"max_count": 3}), "No word may appear more than 3 times in your entire response."),
            (("no_commas", "forbidden_char", {"char": ","}), "Do not use any commas."),
            (("keyword_milk_2x", "keyword_min_count", {"word": "milk", "min_count": 2}), "Include the word 'milk' at least twice."),
            (("keyword_horns", "keyword_min_count", {"word": "horns", "min_count": 1}), "Include the word 'horns' at least once."),
            (("exactly_5_sentences", "count_sentences", {"target": 5}), "Your response must be exactly 5 sentences long."),
            (("words_per_sentence_8_16", "words_per_sentence_range", {"min_w": 8, "max_w": 16}), "Each sentence must be between 8 and 16 words long."),
            (("different_start_letters", "sentences_start_different_letter", {}), "Each sentence must start with a different letter."),
        ],
    },
    {
        "id": "mountain_herd_animal",
        "topic": "a sure-footed mountain herd animal",
        "base_instruction": "Describe a sure-footed mountain herd animal crossing rocky slopes.",
        "ordered_checks": [
            (("long_word_per_sentence", "sentences_contain_long_word", {"min_length": 5}), "Each sentence must contain at least one word with 5 or more letters."),
            (("min_25_unique", "min_unique_words", {"min_unique": 25}), "You must use at least 25 unique words."),
            (("max_word_freq_3", "max_word_frequency", {"max_count": 3}), "No word may appear more than 3 times in your entire response."),
            (("no_exclamation", "forbidden_char", {"char": "!"}), "Do not use any exclamation marks."),
            (("all_lowercase", "all_lowercase", {}), "Your entire response must be in all lowercase."),
            (("keyword_cliff", "keyword_min_count", {"word": "cliff", "min_count": 1}), "Include the word 'cliff' at least once."),
            (("keyword_hooves", "keyword_min_count", {"word": "hooves", "min_count": 1}), "Include the word 'hooves' at least once."),
            (("exactly_4_sentences", "count_sentences", {"target": 4}), "Your response must be exactly 4 sentences long."),
            (("words_per_sentence_10_20", "words_per_sentence_range", {"min_w": 10, "max_w": 20}), "Each sentence must be between 10 and 20 words long."),
        ],
    },
    {
        "id": "barnyard_riddle",
        "topic": "a barnyard riddle about a bearded animal",
        "base_instruction": "Write a riddle about a bearded barnyard animal with horns and split hooves.",
        "ordered_checks": [
            (("long_word_per_line", "numbered_items_contain_long_word", {"min_length": 5}), "Each clue must contain at least one word with 5 or more letters."),
            (("min_18_unique", "min_unique_words", {"min_unique": 18}), "You must use at least 18 unique words."),
            (("max_word_freq_3", "max_word_frequency", {"max_count": 3}), "No word may appear more than 3 times in your entire response."),
            (("no_commas", "forbidden_char", {"char": ","}), "Do not use any commas."),
            (("keyword_beard", "keyword_min_count", {"word": "beard", "min_count": 1}), "Include the word 'beard' at least once."),
            (("keyword_hooves", "keyword_min_count", {"word": "hooves", "min_count": 1}), "Include the word 'hooves' at least once."),
            (("exactly_4_numbered", "count_numbered_items", {"target": 4}), "Give exactly 4 clues. Number each clue starting from 1."),
            (("clue_words_6_14", "numbered_items_word_range", {"min_w": 6, "max_w": 14}), "Each clue must be between 6 and 14 words long."),
            (("each_clue_one_sentence", "numbered_items_one_sentence", {}), "Each clue must be exactly one sentence."),
        ],
    },
    {
        "id": "pasture_cheese_notes",
        "topic": "notes about pasture milk and cheese",
        "base_instruction": "Write tasting notes for fresh cheese made from pasture milk.",
        "ordered_checks": [
            (("long_word_per_sentence", "sentences_contain_long_word", {"min_length": 5}), "Each sentence must contain at least one word with 5 or more letters."),
            (("min_20_unique", "min_unique_words", {"min_unique": 20}), "You must use at least 20 unique words."),
            (("max_word_freq_3", "max_word_frequency", {"max_count": 3}), "No word may appear more than 3 times in your entire response."),
            (("no_exclamation", "forbidden_char", {"char": "!"}), "Do not use any exclamation marks."),
            (("keyword_cheese_2x", "keyword_min_count", {"word": "cheese", "min_count": 2}), "Include the word 'cheese' at least twice."),
            (("keyword_tangy", "keyword_min_count", {"word": "tangy", "min_count": 1}), "Include the word 'tangy' at least once."),
            (("exactly_4_sentences", "count_sentences", {"target": 4}), "Your response must be exactly 4 sentences long."),
            (("words_per_sentence_9_18", "words_per_sentence_range", {"min_w": 9, "max_w": 18}), "Each sentence must be between 9 and 18 words long."),
            (("different_start_letters", "sentences_start_different_letter", {}), "Each sentence must start with a different letter."),
        ],
    },
    {
        "id": "zoo_placard",
        "topic": "a zoo placard for a playful horned mammal",
        "base_instruction": "Write a zoo placard for a playful horned mammal with rectangular pupils and climbing skills.",
        "ordered_checks": [
            (("long_word_per_sentence", "sentences_contain_long_word", {"min_length": 5}), "Each sentence must contain at least one word with 5 or more letters."),
            (("min_25_unique", "min_unique_words", {"min_unique": 25}), "You must use at least 25 unique words."),
            (("max_word_freq_3", "max_word_frequency", {"max_count": 3}), "No word may appear more than 3 times in your entire response."),
            (("no_commas", "forbidden_char", {"char": ","}), "Do not use any commas."),
            (("keyword_pupils", "keyword_min_count", {"word": "pupils", "min_count": 1}), "Include the word 'pupils' at least once."),
            (("keyword_climbing", "keyword_min_count", {"word": "climbing", "min_count": 1}), "Include the word 'climbing' at least once."),
            (("exactly_4_sentences", "count_sentences", {"target": 4}), "Your response must be exactly 4 sentences long."),
            (("words_per_sentence_10_18", "words_per_sentence_range", {"min_w": 10, "max_w": 18}), "Each sentence must be between 10 and 18 words long."),
            (("different_start_letters", "sentences_start_different_letter", {}), "Each sentence must start with a different letter."),
        ],
    },
    {
        "id": "cheesemaker_interview",
        "topic": "an interview with a cheesemaker",
        "base_instruction": "Write a brief interview with a cheesemaker who uses milk from small horned animals.",
        "ordered_checks": [
            (("long_word_per_item", "numbered_items_contain_long_word", {"min_length": 5}), "Each interview answer must contain at least one word with 5 or more letters."),
            (("min_25_unique", "min_unique_words", {"min_unique": 25}), "You must use at least 25 unique words."),
            (("max_word_freq_3", "max_word_frequency", {"max_count": 3}), "No word may appear more than 3 times in your entire response."),
            (("no_exclamation", "forbidden_char", {"char": "!"}), "Do not use any exclamation marks."),
            (("keyword_cheese_2x", "keyword_min_count", {"word": "cheese", "min_count": 2}), "Include the word 'cheese' at least twice."),
            (("keyword_milk_2x", "keyword_min_count", {"word": "milk", "min_count": 2}), "Include the word 'milk' at least twice."),
            (("exactly_4_numbered", "count_numbered_items", {"target": 4}), "Give exactly 4 interview answers. Number each answer starting from 1."),
            (("answer_words_9_18", "numbered_items_word_range", {"min_w": 9, "max_w": 18}), "Each interview answer must be between 9 and 18 words long."),
            (("each_answer_one_sentence", "numbered_items_one_sentence", {}), "Each interview answer must be exactly one sentence."),
        ],
    },
    {
        "id": "petting_farm_guide",
        "topic": "a petting farm guide for children",
        "base_instruction": "Write safety tips for children visiting a petting farm enclosure with small hoofed animals.",
        "ordered_checks": [
            (("long_word_per_tip", "numbered_items_contain_long_word", {"min_length": 5}), "Each tip must contain at least one word with 5 or more letters."),
            (("min_18_unique", "min_unique_words", {"min_unique": 18}), "You must use at least 18 unique words."),
            (("max_word_freq_3", "max_word_frequency", {"max_count": 3}), "No word may appear more than 3 times in your entire response."),
            (("no_commas", "forbidden_char", {"char": ","}), "Do not use any commas."),
            (("keyword_gentle", "keyword_min_count", {"word": "gentle", "min_count": 1}), "Include the word 'gentle' at least once."),
            (("keyword_feed", "keyword_min_count", {"word": "feed", "min_count": 1}), "Include the word 'feed' at least once."),
            (("exactly_3_numbered", "count_numbered_items", {"target": 3}), "Give exactly 3 tips. Number each tip starting from 1."),
            (("tip_words_10_18", "numbered_items_word_range", {"min_w": 10, "max_w": 18}), "Each tip must be between 10 and 18 words long."),
            (("each_tip_one_sentence", "numbered_items_one_sentence", {}), "Each tip must be exactly one sentence."),
        ],
    },
]
