PROMPTS = [
    {
        "id": "exercise",
        "topic": "the benefits of exercise",
        "base_instruction": "Write a short response about the benefits of exercise.",
        "ordered_checks": [
            (("long_word_per_sentence", "sentences_contain_long_word", {"min_length": 5}), "Each sentence must contain at least one word with 5 or more letters."),
            (("min_20_unique", "min_unique_words", {"min_unique": 20}), "You must use at least 20 unique words."),
            (("max_word_freq_3", "max_word_frequency", {"max_count": 3}), "No word may appear more than 3 times in your entire response."),
            (("no_commas", "forbidden_char", {"char": ","}), "Do not use any commas."),
            (("all_lowercase", "all_lowercase", {}), "Your entire response must be in all lowercase."),
            (("keyword_energy_2x", "keyword_min_count", {"word": "energy", "min_count": 2}), "Include the word 'energy' at least twice."),
            (("exactly_5_sentences", "count_sentences", {"target": 5}), "Your response must be exactly 5 sentences long."),
            (("words_per_sentence_8_15", "words_per_sentence_range", {"min_w": 8, "max_w": 15}), "Each sentence must be between 8 and 15 words long."),
            (("different_start_letters", "sentences_start_different_letter", {}), "Each sentence must start with a different letter."),
        ],
    },
    {
        "id": "book_review",
        "topic": "a book review",
        "base_instruction": "Write a short review of a book you have read.",
        "ordered_checks": [
            (("long_word_per_sentence", "sentences_contain_long_word", {"min_length": 5}), "Each sentence must contain at least one word with 5 or more letters."),
            (("min_25_unique", "min_unique_words", {"min_unique": 25}), "You must use at least 25 unique words."),
            (("max_word_freq_3", "max_word_frequency", {"max_count": 3}), "No word may appear more than 3 times in your entire response."),
            (("no_commas", "forbidden_char", {"char": ","}), "Do not use any commas."),
            (("all_uppercase", "all_uppercase", {}), "Your entire response must be in all uppercase letters."),
            (("keyword_RECOMMEND", "keyword_min_count_case_sensitive", {"word": "RECOMMEND", "min_count": 1}), "Include the word 'RECOMMEND' at least once."),
            (("exactly_4_sentences", "count_sentences", {"target": 4}), "Your response must be exactly 4 sentences long."),
            (("words_per_sentence_10_20", "words_per_sentence_range", {"min_w": 10, "max_w": 20}), "Each sentence must be between 10 and 20 words long."),
            (("different_start_letters", "sentences_start_different_letter", {}), "Each sentence must start with a different letter."),
        ],
    },
    {
        "id": "language_tips",
        "topic": "tips for learning a new language",
        "base_instruction": "Give tips for learning a new language.",
        "ordered_checks": [
            (("long_word_per_tip", "numbered_items_contain_long_word", {"min_length": 5}), "Each tip must contain at least one word with 5 or more letters."),
            (("min_15_unique", "min_unique_words", {"min_unique": 15}), "You must use at least 15 unique words."),
            (("max_word_freq_3", "max_word_frequency", {"max_count": 3}), "No word may appear more than 3 times in your entire response."),
            (("no_letter_z", "forbidden_char_insensitive", {"char": "z"}), "Do not use the letter 'z' anywhere in your response."),
            (("exactly_3_numbered", "count_numbered_items", {"target": 3}), "Give exactly 3 tips. Number each tip starting from 1."),
            (("tip_words_10_20", "numbered_items_word_range", {"min_w": 10, "max_w": 20}), "Each tip must be between 10 and 20 words long."),
            (("each_tip_one_sentence", "numbered_items_one_sentence", {}), "Each tip must be exactly one sentence."),
        ],
    },
    {
        "id": "season",
        "topic": "describing a favorite season",
        "base_instruction": "Describe your favorite season.",
        "ordered_checks": [
            (("long_word_per_sentence", "sentences_contain_long_word", {"min_length": 5}), "Each sentence must contain at least one word with 5 or more letters."),
            (("min_25_unique", "min_unique_words", {"min_unique": 25}), "You must use at least 25 unique words."),
            (("max_word_freq_3", "max_word_frequency", {"max_count": 3}), "No word may appear more than 3 times in your entire response."),
            (("no_exclamation", "forbidden_char", {"char": "!"}), "Do not use any exclamation marks."),
            (("keyword_weather", "keyword_min_count", {"word": "weather", "min_count": 1}), "Include the word 'weather' at least once."),
            (("exactly_4_sentences", "count_sentences", {"target": 4}), "Your response must be exactly 4 sentences long."),
            (("words_per_sentence_10_20", "words_per_sentence_range", {"min_w": 10, "max_w": 20}), "Each sentence must be between 10 and 20 words long."),
            (("different_start_letters", "sentences_start_different_letter", {}), "Each sentence must start with a different letter."),
            (("ends_with_phrase", "ends_with_phrase", {"phrase": "That is why I love this season more than any other."}), "Finish your response with the exact phrase 'That is why I love this season more than any other.'"),
        ],
    },
    {
        "id": "recycling",
        "topic": "why recycling is important",
        "base_instruction": "Write a short response about why recycling is important.",
        "ordered_checks": [
            (("long_word_per_sentence", "sentences_contain_long_word", {"min_length": 5}), "Each sentence must contain at least one word with 5 or more letters."),
            (("min_25_unique", "min_unique_words", {"min_unique": 25}), "You must use at least 25 unique words."),
            (("max_word_freq_3", "max_word_frequency", {"max_count": 3}), "No word may appear more than 3 times in your entire response."),
            (("no_exclamation", "forbidden_char", {"char": "!"}), "Do not use any exclamation marks."),
            (("all_lowercase", "all_lowercase", {}), "Your entire response must be in all lowercase."),
            (("keyword_environment_3x", "keyword_min_count", {"word": "environment", "min_count": 3}), "Include the word 'environment' at least 3 times."),
            (("exactly_5_sentences", "count_sentences", {"target": 5}), "Your response must be exactly 5 sentences long."),
            (("words_per_sentence_8_15", "words_per_sentence_range", {"min_w": 8, "max_w": 15}), "Each sentence must be between 8 and 15 words long."),
            (("different_start_letters", "sentences_start_different_letter", {}), "Each sentence must start with a different letter."),
        ],
    },
]
